name       : libao
version    : 1.2.2
release    : 9
source     :
    - https://github.com/xiph/libao/archive/1.2.2.tar.gz : df8a6d0e238feeccb26a783e778716fb41a801536fe7b6fce068e313c0e2bf4d
license    : GPL-2.0
component  : multimedia.library
summary    : Libao is a cross-platform audio library that allows programs to output audio
description: |
    Libao is a cross-platform audio library that allows programs to output audio
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libpulse)
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration-on-Solus.patch
    %patch -p1 < $pkgfiles/security/CVE-2017-11548.patch
    %reconfigure --disable-static --enable-alsa-mmap
build      : |
    %make
install    : |
    %make_install
    install -Dm644 $pkgfiles/libao.conf $installdir/usr/share/defaults/libao/libao.conf
