name       : libao
version    : 1.2.0
release    : 2
source     :
    - http://downloads.xiph.org/releases/ao/libao-1.2.0.tar.gz : 03ad231ad1f9d64b52474392d63c31197b0bc7bd416e58b1c10a329a5ed89caf
license    : GPL-2.0
component  : multimedia.library
summary    : Libao is a cross-platform audio library that allows programs to output
    audio
description: |
    Libao is a cross-platform audio library that allows programs to output audio
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libpulse)
setup      : |
    %configure --disable-static --enable-alsa-mmap
build      : |
    %make
install    : |
    %make_install
    install -Dm644 $srcdir/libao.conf* $installdir/etc/libao.conf
